version: '3.1'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    security_opt:
      - seccomp:unconfined
    networks:
      - inner-res
    ports:
      - "3306:3306"
    volumes:
      - /home/xx/work/dycms/mysql/conf:/etc/mysql/conf.d
      - /home/xx/work/dycms/mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xx

  php:
    image: bitnami/php-fpm:8.1.20
    container_name: php-fpm
    networks:
      - inner-res
    restart: always

  dycms-php:
    image: xx/dycms-php:latest
    container_name: dycms-php
    networks:
      - inner-res
    depends_on:
      - db
    restart: always

  caddy:
    image: caddy:latest
    container_name: caddy
    networks:
      - inner-res
    ports:
      - "80:80"
    volumes:
      - /home/xx/work/dycms/Caddyfile:/etc/caddy/Caddyfile
      - /home/xx/work/dycms/dycms-html:/var/www
    restart: always

networks:
  inner-res:
